# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
  pipelines:
    - pipeline: CI
      source: 'ebrahim22586.azure-devops-github-acr-aks-app1'
      trigger: true 

variables:
  dockerRegistryServiceConnection: 'f4982ffe-8e2d-4b57-bfe8-2fcaaf341eb5'
  imageRepository: 'acrimageun'
  containerRegistry: 'acrforaksun.azurecr.io'
  secretName: 'imgpullsecaks'
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

steps:

- download: CI
  artifact: aksfiles

- bash: |
    IMAGE_TAG=$(cat $(Pipeline.Workspace)/CI/aksfiles/imageTag.txt)

    echo "Image Tag = $IMAGE_TAG"

    echo "##vso[task.setvariable variable=imageTag]$IMAGE_TAG"
  displayName: Read Image Tag

- task: KubernetesManifest@1
  inputs:
    action: 'createSecret'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'dev-ns-k8s-aks-svc-conn'
    namespace: 'dev'
    secretType: 'dockerRegistry'
    secretName: '$(secretName)'
    dockerRegistryEndpoint: '$(dockerRegistryServiceConnection)'

- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'dev-ns-k8s-aks-svc-conn'
    namespace: 'dev'
    manifests: '$(Build.ArtifactStagingDirectory)/aksfiles/appwithservice.yml'
    containers: '$(containerRegistry)/$(imageRepository):$(imageTag)'
    imagePullSecrets: '$(secretName)'
