# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '660a7ac6-4ae2-4071-9db0-e69a9c241c15'
  imageRepository: 'ebrahimazuredevopsgithubacraksapp'
  containerRegistry: 'acrforaksun.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)


    - upload: mainfests
      artifact: mainfests


- stage: Deploy
  displayName: DeployStage
  dependsOn: Build
  jobs:
    - deployment: Deploy
      displayName: DeployToAKS
      pool:
       vmImage: $(vmImageName)
      environment: env-aks-dev
      strategy: 
       runOnce:
         deploy:
           steps:
             - task: KubernetesManifest@1
               displayName: CreateImageSecret
               inputs:
                  action: createSecret
                  secretName: $(imagePullSecret)
                  dockerRegistryEndpoint: $(dockerRegistryServiceConnection) 

             - task: KubernetesManifest@1
               displayName: DeployToAks
               inputs:
                 action: deploy
                 manifests: |
                   $(Pipeline.Workspaces)/mainfests/deployment.yml
                   $(Pipeline.Workspaces)/mainfests/service.yml

                 imagePullSecrets: |
                   $(imageRepository)
                 containers: |
                   $(containerRegistry)/$(imageRepository):$(tag)                      
